name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'

        - name: Download LocalAI
          run: |
            curl -OL https://github.com/mudler/LocalAI/releases/download/v1.40.0/local-ai-avx2-Linux-x86_64
            file ./local-ai-avx2-Linux-x86_64
            chmod +x ./local-ai-avx2-Linux-x86_64

        - name: Download Orca Mini 3B model
          run: |
            curl -OL https://huggingface.co/TheBloke/orca_mini_3B-GGML/resolve/main/orca-mini-3b.ggmlv3.q4_0.bin
            mkdir models
            mv ./orca-mini-3b.ggmlv3.q4_0.bin ./models/

        - name: Run LocalAI with Orca Mini 3B
          run: |
            ./local-ai-avx2-Linux-x86_64 --threads 2 --models-path ./models
            sleep 5

        - name: Check the available models
          run: curl --silent localhost:8080/v1/models | jq

        - run: npm ci

        - run: npm start "Indonesia declared its independence on"
          timeout-minutes: 7
          env:
            OPENAI_API_BASE: "http://127.0.0.1:8080"
            CHAT_MODEL: "orca-mini-3b.ggmlv3.q4_0.bin"