name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'

        - name: Download Mistral 7B model
          run: curl -OL https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-GGUF/resolve/main/mistral-7b-openorca.Q3_K_M.gguf

        - name: Install Nitro
          run: npm install @janhq/nitro

        - name: Launch Nitro
          run: ./node_modules/@janhq/nitro/nitro &

        - name: Wait until Nitro is ready
          run: while ! curl -s 'http://localhost:3928/healthz' | grep 'alive'; do sleep 1; done
          timeout-minutes: 3

        - name: Load Mistral 7B into Nitro
          run: |
            curl http://localhost:3928/inferences/llamacpp/loadmodel \
              -H 'Content-Type: application/json' \
              -d '{"llama_model_path": "./mistral-7b-openorca.Q3_K_M.gguf"}'

        - run: npm ci

        - run: npm start "Which planet in our solar system is the largest?" | grep Jupiter
          timeout-minutes: 7
          env:
            OPENAI_API_BASE: "http://127.0.0.1:3928"
